export const MenuDetailUIItems = [
  { text: "Components", icon: "la la-cubes" },
  { text: "Input Groups", icon: "la la-stop" },
  { text: "Layout", icon: "la la-th-large" },
  { text: "Validations", icon: "la la-check-circle" },
  { text: "Wizards", icon: "la la-hand-pointer" },
  { text: "Alerts", icon: "la la-bell" },
  { text: "Avatars", icon: "la la-user-circle" },
  { text: "Badges", icon: "la la-certificate" },
  { text: "Buttons", icon: "la la-play" },
  { text: "Cards", icon: "la la-layer-group" },
  { text: "Collapse", icon: "la la-arrow-circle-right" },
  { text: "Colors", icon: "la la-palette" },
  { text: "Dropdowns", icon: "la la-arrow-circle-down" },
  { text: "Modal", icon: "la la-times-circle" },
  { text: "Popovers & Tooltips", icon: "la la-thumbtack" },
  { text: "Tabs", icon: "la la-columns" },
  { text: "Tables", icon: "la la-table" },
  { text: "Toasts", icon: "la la-bell" },
  { text: "Carousel", icon: "la la-images" },
  { text: "Charts", icon: "la la-chart-area" },
  { text: "Editors", icon: "la la-keyboard" },
  { text: "FullCalendar", icon: "la la-calendar" },
  { text: "Sortable", icon: "la la-sort" },
];

export const MenuDetailPagesItems = [
  { text: "Login", icon: "la la-user" },
  { text: "Forgot Password", icon: "la la-user-lock" },
  { text: "Register", icon: "la la-user-plus" },
  { text: "List", icon: "la la-list" },
  { text: "List - Card Rows", icon: "la la-list" },
  { text: "List - Card Columns", icon: "la la-list" },
  { text: "Add Post", icon: "la la-layer-group" },
  { text: "403 Error", icon: "la la-exclamation-circle" },
  { text: "404 Error", icon: "la la-exclamation-circle" },
  { text: "500 Error", icon: "la la-exclamation-circle" },
  { text: "Under Maintenance", icon: "la la-exclamation-circle" },
  { text: "Pricing", icon: "la la-dollar" },
  { text: "FAQs - Layout 1", icon: "la la-question-circle" },
  { text: "FAQs - Layout 2", icon: "la la-question-circle" },
  { text: "Invoice", icon: "la la-file-invoice-dollar" },
];

export const MenuDetailApplicationsItems = [
  { text: "Media Library", icon: "la la-image" },
  { text: "Point Of Sale", icon: "la la-shopping-bag" },
  { text: "To Do", icon: "la la-check-circle" },
  { text: "Chat", icon: "la la-comment" },
];

export const MenuDetailMenuItems = [
  { text: "Default", icon: "la la-cube" },
  { text: "Content", icon: "la la-file-alt" },
  { text: "Ecommerce", icon: "la la-shopping-bag" },
];

export const MenuDetailMenuTypes = [
  { type: "default", icon: "la la-hand-point-right", label: "Default" },
  { type: "hidden", icon: "la la-hand-point-left", label: "Hidden" },
  { type: "icon-only", icon: "la la-th-large", label: "Icon Only" },
  { type: "wide", icon: "la la-arrows-alt-h", label: "Wide" },
];

export const files = [
  {
    id: 1,
    name: "Potato",
    type: null,
    size: 525,
    createdDateTime: "1631979705",
    updatedDateTime: "1645328968",
  },
  {
    id: 2,
    name: "Tomato",
    type: null,
    size: 735,
    createdDateTime: "1650404171",
    updatedDateTime: "1651391061",
  },
  {
    id: 3,
    name: "Pepper",
    type: null,
    size: 362,
    createdDateTime: "1649725555",
    updatedDateTime: "1639408626",
  },
  {
    id: 4,
    name: "Ingredients.mp3",
    type: "audio/mp3",
    size: 378,
    createdDateTime: "1658427925",
    updatedDateTime: "1657312397",
  },
  {
    id: 5,
    name: "Garlic.mp4",
    type: "video/mp4",
    size: 969,
    createdDateTime: "1650158725",
    updatedDateTime: "1650824920",
  },
  {
    id: 6,
    name: "Onion.pdf",
    type: "document/pdf",
    size: 435,
    createdDateTime: "1642823304",
    updatedDateTime: "1636433608",
  },
  {
    id: 7,
    name: "Potato.jpg",
    type: "image/jpg",
    size: 410,
    createdDateTime: "1659756670",
    updatedDateTime: "1655058865",
  },
  {
    id: 8,
    name: "Tomato.jpg",
    type: "image/jpg",
    size: 276,
    createdDateTime: "1640076944",
    updatedDateTime: "1641951868",
  },
  {
    id: 9,
    name: "Pepper.jpg",
    type: "image/jpg",
    size: 852,
    createdDateTime: "1655010548",
    updatedDateTime: "1630483517",
  },
  {
    id: 10,
    name: "Ingredients.jpg",
    type: "image/jpg",
    size: 538,
    createdDateTime: "1635580930",
    updatedDateTime: "1655662199",
  },
  {
    id: 11,
    name: "Garlic.jpg",
    type: "image/jpg",
    size: 104,
    createdDateTime: "1651105915",
    updatedDateTime: "1653783049",
  },
  {
    id: 12,
    name: "Breakfast.jpg",
    type: "image/jpg",
    size: 296,
    createdDateTime: "1632515855",
    updatedDateTime: "1652253810",
  },
  {
    id: 13,
    name: "Onion.jpg",
    type: "image/jpg",
    size: 523,
    createdDateTime: "1653605654",
    updatedDateTime: "1645037229",
  },
  {
    id: 14,
    name: "Pepper Flower.jpg",
    type: "image/jpg",
    size: 345,
    createdDateTime: "1645811838",
    updatedDateTime: "1655894442",
  },
  {
    id: 15,
    name: "Potato.jpg",
    type: "image/jpg",
    size: 598,
    createdDateTime: "1630005280",
    updatedDateTime: "1632678752",
  },  {
    id: 16,
    name: "Garlic.jpg",
    type: "image/jpg",
    size: 104,
    createdDateTime: "1651105915",
    updatedDateTime: "1653783049",
  },
  {
    id: 17,
    name: "Breakfast.jpg",
    type: "image/jpg",
    size: 296,
    createdDateTime: "1632515855",
    updatedDateTime: "1652253810",
  },
];
